
FROM nginx:alpine

# Копируем наш конфигурационный файл в контейнер
COPY nginx.conf /etc/nginx/nginx.conf

COPY realCerts/server.crt /etc/nginx/certs/server.crt
COPY realCerts/server.key /etc/nginx/certs/server.key

# Указываем порт
EXPOSE 80
EXPOSE 443