version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_new
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: money_transfer_database_V2

    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d money_transfer_database']
      interval: 10s
      timeout: 10s
      retries: 10

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - '8080:8080'
    depends_on:
      - postgres
