version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: postgres_db_new
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      PG_PORT: ${DB_PORT}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U user -d money_transfer_database_V2']
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    build: .
    container_name: backend_container
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_NAME: ${DB_NAME}
      PORT: ${PORT}
    depends_on:
      postgres:
        condition: service_healthy

  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    container_name: nginx_container
    ports:
      - '80:80'
      - '443:443'
    depends_on:
      - backend

volumes:
  postgres_data:
